import type { Metadata } from "next";
import "./globals.css";
import Copyright from "./components/Copyright";

export const metadata: Metadata = {
  title: "Nongtoy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        <Copyright />
      </body>
    </html>
  );
}
